# Auto Stock Backtest Configuration
backtest:
  # 基本設定
  start_date: "2005-01-01"
  end_date: null  # nullの場合は現在日付
  cash: 100000
  commission: 0.002
  slippage: 0.001  # スリッページ（0.1%）
  
  # データ取得設定
  data:
    retry_attempts: 3
    retry_delay: 60  # 秒
    rate_limit_delay: 1  # 秒
    cache_duration: 86400  # 24時間（秒）
    
  # Walk-Forward設定
  walkforward:
    train_years: 5
    test_years: 1
    step_years: 1
    min_data_points: 20
    
  # サンプリング設定
  sampling:
    sample_size: 12
    oos_random_size: 8
    holdout_months: 12
    stratification: true
    
  # リスク管理設定
  risk_management:
    max_position_size: 0.1  # 最大ポジションサイズ（資金の10%）
    max_drawdown_limit: 0.2  # 最大ドローダウン制限（20%）
    stop_loss: 0.05  # 損切り（5%）
    take_profit: 0.15  # 利確（15%）
  
  # AI改善設定
  ai_improvement:
    similarity_threshold: 0.9  # 類似提案の閾値
    max_improvements_per_run: 3  # 1回の実行での最大改善提案数
    improvement_score_threshold: 0.05  # 改善スコアの閾値
    enable_rollback: true  # ロールバック機能の有効化

# 戦略設定
strategies:
  FixedSma:
    enabled: true
    params:
      sma_period: [8, 18, 30, 50]  # 改善: 10→8, 20→18
    risk_management:
      enabled: false
      
  SmaCross:
    enabled: true
    params:
      n_fast: [15, 30, 40]  # 改善: 20→15
      n_slow: [45, 60, 80, 100]  # 改善: 50→45
    risk_management:
      enabled: true
      
  Momentum:
    enabled: false  # 今後追加予定
    params:
      rsi_period: [14, 21]
      rsi_oversold: [20, 30]
      rsi_overbought: [70, 80]
    risk_management:
      enabled: true

# 銘柄リスト設定
universe:
  # 基本銘柄リスト
  master_universe:
    us_core:
      - "SPY"  # S&P 500 ETF
      - "QQQ"  # NASDAQ-100 ETF
      - "DIA"  # Dow Jones ETF
      - "IWM"  # Russell 2000 ETF
      - "AAPL"  # Apple
      - "MSFT"  # Microsoft
      - "GOOGL"  # Alphabet
      - "AMZN"  # Amazon
      - "META"  # Meta
      - "NFLX"  # Netflix
      - "NVDA"  # NVIDIA
      - "AMD"   # AMD
      - "AVGO"  # Broadcom
      - "TSM"   # TSMC
      - "ASML"  # ASML
      - "INTC"  # Intel
      - "QCOM"  # Qualcomm
      - "MU"    # Micron
      - "ARM"   # ARM
      - "SMCI"  # Super Micro Computer
      - "PLTR"  # Palantir
      - "SNOW"  # Snowflake
      - "CRM"   # Salesforce
      - "ADBE"  # Adobe
      - "ORCL"  # Oracle
      - "SHOP"  # Shopify
      
    jp_core:
      - "7203.T"  # トヨタ自動車
      - "6758.T"  # ソニーグループ
      - "9984.T"  # ソフトバンクグループ
      - "8035.T"  # 東京エレクトロン
      - "6954.T"  # ファナック
      - "4063.T"  # 信越化学工業
      - "7735.T"  # スクリーンホールディングス
      - "6920.T"  # レーザーテック
      - "6857.T"  # アドバンテスト
      - "4523.T"  # エーザイ
      - "6501.T"  # 日立製作所
      - "9432.T"  # NTT
      - "9433.T"  # KDDI
      - "9434.T"  # ソフトバンク
      - "2914.T"  # 日本たばこ産業
      - "4502.T"  # 武田薬品工業
      - "3382.T"  # セブン＆アイ・ホールディングス
      - "8306.T"  # 三菱UFJフィナンシャル・グループ
      - "8316.T"  # 三井住友フィナンシャルグループ
      - "8411.T"  # みずほフィナンシャルグループ
      - "8591.T"  # オリックス
      
  # AI関連銘柄
  ai_universe:
    us_ai:
      - "NVDA"  # NVIDIA
      - "AMD"   # AMD
      - "AVGO"  # Broadcom
      - "MSFT"  # Microsoft
      - "GOOGL"  # Alphabet
      - "META"  # Meta
      - "AMZN"  # Amazon
      - "TSM"   # TSMC
      - "ASML"  # ASML
      - "ARM"   # ARM
      - "PLTR"  # Palantir
      - "SNOW"  # Snowflake
      - "SMCI"  # Super Micro Computer
      - "CRM"   # Salesforce
      - "ADBE"  # Adobe
      
    jp_ai:
      - "8035.T"  # 東京エレクトロン
      - "6920.T"  # レーザーテック
      - "6857.T"  # アドバンテスト
      - "7735.T"  # スクリーンホールディングス
      - "9984.T"  # ソフトバンクグループ
      - "6758.T"  # ソニーグループ
      - "4063.T"  # 信越化学工業
      - "6526.T"  # ソシオネクスト
      - "6619.T"  # ワコム

# 評価指標設定
metrics:
  # 基本指標
  basic:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "calmar_ratio"
    - "max_drawdown"
    - "total_return"
    - "annualized_return"
    - "volatility"
    
  # 取引指標
  trading:
    - "win_rate"
    - "profit_factor"
    - "average_trade"
    - "largest_win"
    - "largest_loss"
    - "consecutive_wins"
    - "consecutive_losses"
    
  # リスク指標
  risk:
    - "var_95"
    - "cvar_95"
    - "var_99"
    - "cvar_99"
    - "downside_deviation"
    - "ulcer_index"
    
  # 安定性指標
  stability:
    - "parameter_stability"
    - "out_of_sample_consistency"
    - "rolling_performance"

# ログ設定
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/backtest.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 通知設定
notifications:
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "${SLACK_CHANNEL}"
    bot_token: "${SLACK_BOT_TOKEN}"
    
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    recipients: []
  
  # AI改善通知設定
  ai_improvement:
    enabled: true
    detailed_reports: true
    notification_level: "all"  # "all", "success_only", "summary_only"

# 出力設定
output:
  # レポート出力
  reports:
    format: ["csv", "json", "html"]
    include_charts: true
    include_equity_curves: true
    
  # アーティファクト保存
  artifacts:
    save_equity_curves: true
    save_trade_logs: true
    save_parameter_evolution: true
    
  # 可視化設定
  visualization:
    theme: "default"  # default, dark, light
    dpi: 150
    format: "png"
    size: [12, 8]
