name: Daily Backtest

on:
  schedule:
    - cron: '0 22 * * *'  # UTC 22:00 = JST 07:00
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch OOS tickers from Slack
        run: python scripts/fetch_oos_from_slack.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CONFIG_CHANNEL: ${{ vars.SLACK_CONFIG_CHANNEL }}
          OOS_FIXED_TICKERS: ${{ vars.OOS_FIXED_TICKERS }}

      - name: Run backtest
        run: python scripts/run_backtest.py
        env:
          SAMPLE_SIZE: ${{ vars.SAMPLE_SIZE }}
          OOS_RANDOM_SIZE: ${{ vars.OOS_RANDOM_SIZE }}
          HOLDOUT_MONTHS: ${{ vars.HOLDOUT_MONTHS }}
          RANDOM_SEED: ${{ vars.RANDOM_SEED }}

      - name: Notify Slack
        run: python scripts/notify_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CONFIG_CHANNEL: ${{ vars.SLACK_CONFIG_CHANNEL }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
